### ISSUE TITLE
Update "Example Usage" section in the documentation

### ISSUE THREAD

**Issue by sriedel** [matthewoden/libvault#16]
I've tried following the steps in the Example Usage section from https://hexdocs.pm/libvault/Vault.html#module-setup-and-usage, and some configurations that seem to be required now  are not present:

- a http client needs to be set explicitly, otherwise the following error pops up:

    > Vault.auth(vault)
    {:error, ["http client not set"]}

- a host needs to be set, otherwise the following error pops up:

    > Vault.auth(vault)
    ** (CaseClauseError) no case clause matching: []
    (hackney 1.16.0) /home/sr/src/example/deps/hackney/src/hackney_url.erl:248: :hackney_url.parse_netloc/2
    (hackney 1.16.0) /home/sr/src/example/deps/hackney/src/hackney.erl:349: :hackney.request/5
    (libvault 0.2.2) lib/vault/http/http.ex:70: Vault.HTTP.request/4
    (libvault 0.2.2) lib/vault/auth/userpass.ex:34: Vault.Auth.UserPass.login/2
    (libvault 0.2.2) lib/vault.ex:366: Vault.auth/2

- Using hackney as http client, setting the engine, auth, credentials and host, I'm now getting 

    > vault = Vault.new([engine: Vault.Engine.KVV2, auth: Vault.Auth.UserPass, credentials: %{username: "user", password: "pass"}, host: "https://myvault.local:8200/", http: :hackney])
    %Vault{
       auth: Vault.Auth.UserPass,   
       auth_path: nil,
      credentials: %{password: "pass", username: "user"},
      engine: Vault.Engine.KVV2,
      host: "https://myvault.local:8200/",
      http: :hackney,
      http_options: [],
      json: Jason,
      token: nil,
      token_expires_at: nil
    }
    iex(2)> Vault.auth(vault)
    ** (ArgumentError) argument error
    (hackney 1.16.0) /home/sr/src/example/deps/hackney/src/hackney_headers_new.erl:47: :hackney_headers_new.new/1
    (hackney 1.16.0) /home/sr/src/example/deps/hackney/src/hackney.erl:331: :hackney.request/5
    (libvault 0.2.2) lib/vault/http/http.ex:70: Vault.HTTP.request/4
    (libvault 0.2.2) lib/vault/auth/userpass.ex:34: Vault.Auth.UserPass.login/2
    (libvault 0.2.2) lib/vault.ex:366: Vault.auth/2

and I don't really know how to continue.

- Also, how would one configure a ca cert for vault instances running with self-signed certificates?

**Comment by matthewoden** [comment]
This is great feedback! I'm more than happy to update the documentation to make it easier to get up and running.

> a http client needs to be set explicitly, otherwise the following error pops up:

The options do state that it defaults to tesla when present, but if you're just running off the example (as most probably will), it should really be explicitly set. 

> a host needs to be set, otherwise the following error pops up:

The host defaults to the VAULT_ADDR environment variable, but I can also have the example code be more explicit about this.

> Using hackney as http client, setting the engine, auth, credentials and host, I'm now getting...

So, at first glance you set `:hackney` as the http client, but what it's looking for is one of the HTTP adapters. A hackney adapter isn't provided by default, but there is one for [tesla](https://hexdocs.pm/libvault/Vault.HTTP.Tesla.html#content), that supports a number of http clients, including hackney. You could use this as example if you would like to write your own for just hackney.

> Also, how would one configure a ca cert for vault instances running with self-signed certificates?

This is a concern of the http adapter - the adapter passes in :http_options to the client. For the Tesla adapter, this would enable you to pass in ssl certs. See [Tesla Client](https://github.com/teamon/tesla#adapter-options) for full options.

**Comment by matthewoden** [comment]
@sriedel Take a gander at  #18 - mostly, whitespace cleanup. The relevant section is here. I've added the http adapter, host, and a line showing how to incorporate self-signed certs. Feedback/suggestions welcome.
https://github.com/matthewoden/libvault/pull/18/files#diff-a67dd9aa11a8b51e853054bc866f8a47R119

Did you have any other usability issues when getting started?

**Comment by sriedel** [comment]
Sorry for the late response, I was out of office for the past two weeks.

Thanks for your explanations, the diff looks good, except that the host value needs to be enclosed in quotation marks.

The explanation with Tesla makes sense. I haven't followed the elixir ecosystem that closely in the past 3 years, but I'm guessing is the  equivalent of faraday in ruby, a common facade in front of different http clients?

And if you're not yet encumbered with a http client dependency, is there any client that you would recommend for or against for use with libvault?

**Comment by sriedel** [comment]
Small feedback on supplying a cacert: I've tried a lot of different permutations of supplying the cacert file both to hackney and to mint via :http_options, all resulting in 

    07:30:09.443 [info]  TLS :client: In state :certify at ssl_handshake.erl:1838 generated CLIENT ALERT: Fatal - Unknown CA    
    
    {:error,
     [
       "Http adapter error",
       {:tls_alert,
        {:unknown_ca,
         'TLS client: In state certify at ssl_handshake.erl:1838 generated CLIENT ALERT: Fatal - Unknown CA\n'}}
     ]}

The only thing thats working for me right now is using Mint and adding to config.exs:

    config :tesla, adapter: Tesla.Adapter.Mint
    config :tesla, Tesla.Adapter.Mint, cacert: ["/path/to/cacert.pem"]

Either the http options are not properly passed through tesla to mint or I'm not building the proper option structure, probably the later. But I can look at that more closely and dig through the tesla and mint code at a later time :)

**Comment by matthewoden** [comment]
> Thanks for your explanations, the diff looks good, except that the host value needs to be enclosed in quotation marks, and :http_options should probably be a keyword list or a map.

Oof. Good catch. I should read my own documentation.

> The explanation with Tesla makes sense. I haven't followed the elixir ecosystem that closely in the past 3 years, but I'm guessing is the equivalent of faraday in ruby, a common facade in front of different http clients?

Yup! That's actually the first line of the README for Tesla. I'm not a ruby person, but ruby seems to have inspired quite a bit of elixir.

> And if you're not yet encumbered with a http client dependency, is there any client that you would recommend for or against for use with libvault?

So I wrote the Tesla Adapter so that folks could stick with whatever http library they're already using. My main goal was to stay out of the user's way. Though if I had to pick, I'd say Mint. Since I generally use Tesla's interface, the main difference between clients comes in the form of compile times. On a normal machine, it's probably not too noticeable. But I've got a dockerized Drone CI agent running on a raspberry pi as part of my home lab - switching to Mint took minutes off my build.

I've only go so much free time for dev in my evenings. So I lean towards whatever helps me keep a lean, iterative cycle in my side projects.
