### ISSUE TITLE
UserPass.login/2 raises "function Tesla.Adapter.Httpc.request/5 is undefined or private"

### ISSUE THREAD

**Issue by marinakr** [matthewoden/libvault#21]
I am trying to get a token with Vault.Auth.UserPass.login/2 but I am getting an error
```
6> client = Vault.new([ engine: Vault.Engine.KVV2, auth: Vault.Auth.UserPass, credentials: %{username: "myuser", password: "psswrd"},http: Tesla.Adapter.Httpc, host: "https://vault.mydomain/"])   

7> Vault.Auth.UserPass.login(client, %{username: "myuser", password: "psswrd"})
** (UndefinedFunctionError) function Tesla.Adapter.Httpc.request/5 is undefined or private
    (tesla 1.3.3) Tesla.Adapter.Httpc.request(:post, "https://ault.mydomain//v1/auth/userpass/login/myuser", "{\"password\":\"psswrd\"}", [{"Content-Type", "application/json"}], [])
    (libvault 0.2.3) lib/vault/http/http.ex:70: Vault.HTTP.request/4
    (libvault 0.2.3) lib/vault/auth/userpass.ex:34: Vault.Auth.UserPass.login/2

```
I am getting this error with `Tesla.Adapter.Hackney` also

```
elixir -v
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.10.4 (compiled with Erlang/OTP 22)
```
``` 
:libvault, "0.2.3"
:tesla, "1.3.3"
```

**Comment by matthewoden** [comment]
So the issue in your config is here:
``` elixir
http: Tesla.Adapter.Httpc
```
You're supplying the Tesla's HTTP adapter to the vault repo. libvault provides an adapter that lets you use tesla, without directly depending on tesla's interface.

To fix this, you should do two things:
1. remove the `http` field from your configuration - since tesla is already present in your app, libvault will detect that, and automatically choose that adapter.
2. supply tesla configuration to the `http_options` as desired. You can pass in middleware, choose an adapter, etc. Here's an example:

``` elixir
Vault.new([
  engine: Vault.Engine.KVV2,
  http_options: [
    adapter: {Tesla.Adapter.Hackney, ssl_options: [cacertfile: "/path/to/file"]},
    middleware: [
      {Tesla.Middleware.Retry, delay: 500, max_retries: 10},
      {Tesla.Middleware.Logger, log_level: :debug},
      {Tesla.Middleware.FollowRedirects, max_redirects: 3}
    ]
  ]
])
```
Closing for now. Feel free to reopen if you have other issues.
